apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lh-pr-checks-pipeline
spec:
  params:
    - name: batch-refs
      type: string
  workspaces:
    - name: source
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-batch-merge
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: "https://github.com/jenkins-x/lighthouse.git"
        - name: batchedRefs
          value: $(params.batch-refs)
        - name: subdirectory
          value: ""
        - name: depth
          value: "0"
    - name: pr-checks
      taskRef:
        name: lh-pr-checks
      runAfter:
        - fetch-repo
      workspaces:
        - name: source
          workspace: source
