{{- if .Values.buildNumbers.enable }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "buildnumbers.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  verbs:
  - get
  - update
  - create
  - list
  - watch
{{- end }}
