apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "foghorn.name" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "foghorn.name" . }}
spec:
  replicas: {{ .Values.foghorn.replicaCount }}
  selector:
    matchLabels:
      draft: {{ default "draft-app" .Values.draft }}
      app: {{ template "foghorn.name" . }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "foghorn.name" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ template "foghorn.name" . }}
      containers:
      - name: {{ template "foghorn.name" . }}
        image: {{ tpl .Values.foghorn.image.repository . }}:{{ tpl .Values.foghorn.image.tag . }}
        imagePullPolicy: {{ tpl .Values.foghorn.image.pullPolicy . }}
        args:
          - "--namespace={{ .Release.Namespace }}"
        env:
          - name: "GIT_KIND"
            value: "{{ .Values.git.kind }}"
          - name: "GIT_SERVER"
            value: "{{ .Values.git.server }}"
          - name: "GIT_USER"
            value: {{ .Values.user }}
          - name: "GIT_TOKEN"
            valueFrom:
              secretKeyRef:
                name: lighthouse-oauth-token
                key: oauth
          - name: "JX_LOG_FORMAT"
            value: "json"
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
{{- end }}
        resources:
{{ toYaml .Values.foghorn.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.foghorn.terminationGracePeriodSeconds }}
{{- with .Values.foghorn.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.foghorn.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.foghorn.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
