{{- if .Values.createIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hook
  annotations:
    kubernetes.io/ingress.class: {{ .Values.hook.ingress.class }}
{{- if .Values.hook.ingress.annotations }}
{{ toYaml .Values.hook.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: hook.{{ .Values.domainName }}
    http:
      paths:
      - backend:
          serviceName: hook
          servicePort: 80
{{- end }}
