{{- if .Values.githubApp.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}-githubapp-tokens
data:
  username: {{ default "jenkins-x[bot]" .Values.githubApp.username | b64enc | quote }}
{{- end }}
